### ISSUE TITLE
Protected directories - via cli

### ISSUE THREAD

**Issue by neural-oD** [virtualmin/virtualmin-htpasswd#2]
Hi,

I've submitted this in forums, but not getting any traction. 
I need to create and remove protected directories via cli. Not too sure on how to achieve this. I've done some reseach, and narrowed it down to: "virtualmin-htpasswd"
Hopefully I'm on the right track. Ideally I'd like to put something into a bash script. 
Any advice would be welcome, or any other suggestions.

ps - Doing this on my "own", as in creating a script just with apache, I'd be worried that, that script could conflict with this one?

**Comment by neural-oD** [comment]
Just updating the link for where I've added this onto the forums:
[https://forum.virtualmin.com/t/how-to-set-up-protected-directories-using-scripts/111891/8](url)

@iliaross @swelljoe

**Comment by jcameron** [comment]
There's no command-line API for this currently, but it's a good idea. I'll look into adding it, and update this bug.

**Comment by neural-oD** [comment]
> There's no command-line API for this currently, but it's a good idea. I'll look into adding it, and update this bug.

That would be so awesome, thanks so much.
I'd offer to look at things, but perl is not in my bag of tools.

**Comment by neural-oD** [comment]
.....sorry Jamie, wasn't sure if by closing this, I'd taken it out of your workflow. Hence reopening it. If you'd prefer to close, just go for it.

**Comment by jcameron** [comment]
I've implemented command-line API support in the protected directories module, which will be in the 3.0 release of this plugin.

You'll be able to use commands like : 

```
virtualmin list-protected-directories
virtualmin create-protected-directory
virtualmin delete-protected-directory
```

and : 

```
virtualmin list-protected-users
virtualmin create-protected-user
virtualmin delete-protected-user
```
