### ISSUE TITLE
Update virtual server admin user password is not calling `modify_user`

### ISSUE THREAD

**Issue by iliaross** [virtualmin/virtualmin-htpasswd#4]
Jamie, hi.

If we update master administrator password using **Edit Virtual Server** page, then user's `public_html/.htpasswd` file is not updated.

If you update mail users, then it all works as expected.

**Comment by jcameron** [comment]
Thanks - I just checked in a fix for this.

**Comment by iliaross** [comment]
Thanks! This fixes the problem!
